#!/bin/bash

set -e

directory=$PWD
cd "$(dirname $0)"

if [ -n "$1" ]
then
    podman build -t generic . 1>&2
    exit
fi

exec podman run -ti \
     --net=host \
     -v $HOME/bin:/root/bin:ro \
     -v $HOME/.bashenv:/root/.bashenv:ro \
     -v $HOME/.bashrc:/root/.bashrc:ro \
     -v $directory:/work \
     generic "$@"
