#!/bin/bash

set -ex

if [ ! -f /usr/bin/docker ]
then
    echo Error: please apt install docker.io >&2
    exit 2
fi

directory=$PWD
cd "$(dirname $0)"

docker build -t generic . 1>&2
exec docker run -ti \
     --net=host \
     -v $directory:/mnt \
     generic "$@"
