#!/bin/bash

set -ex

NAME=ftl

if [ ! -f /usr/bin/podman ]
then
    echo Error: please apt install podman >&2
    exit 2
fi

cd "$(dirname $0)"

podman build -t $NAME . 1>&2

mkdir -p $HOME/.local/share/FasterThanLight

exec podman run -ti \
     --net=host \
     -e DISPLAY=$DISPLAY \
     --device /dev/dri \
     --device /dev/snd \
     --group-add $(getent group audio | cut -d: -f3) \
     -v /tmp/.X11-unix:/tmp/.X11-unix \
     -v $HOME/.Xauthority:/home/.Xauthority \
     -v $HOME/.local/share/FasterThanLight:/home/.local/share/FasterThanLight \
     -v $HOME/Games:/Games \
     $NAME "$@"
#     -u $(id -u):$(id -g) \
