import = ["~/.config/alacritty/my_gruvbox_light.toml"]

[window]
dimensions = {columns=80, lines=24}
decorations = "Full"
resize_increments = true

[font]
#normal = {family="MonaspaceArgon", style="Regular"}
normal = {family="Monaspace Argon Frozen", style="Regular"}
size = 10

[selection]
save_to_clipboard = true
