# git clone https://github.com/alacritty/alacritty-theme \
#  ~/Third-party/alacritty-theme
#import = ["~/Third-party/alacritty-theme/themes/pencil_light.toml"]
#import = ["~/Third-party/alacritty-theme/themes/papercolor_light.toml"]
#import = ["~/Third-party/alacritty-theme/themes/noctis_lux.toml"]
import = ["~/Third-party/alacritty-theme/themes/dayfox.toml"]
#import = ["~/Third-party/alacritty-theme/themes/alabaster.toml"]

[window]
dimensions = {columns=80, lines=24}
decorations = "Full"

[font]
normal = {family="MonaspiceArNerdFontMono", style="Regular"}
size = 10

[selection]
save_to_clipboard = true
