#!/bin/bash

cd /sys/class/power_supply

check () {
    if [ "$(cat AC/online)" == "1" ]
    then return
    fi
    for bat in BAT*
    do
        source <(sed "s/=/='/;s/$/'/" "$bat/uevent")
        if [ "$POWER_SUPPLY_STATUS" == "Charging" ]
        then return
        fi
        if [ "$POWER_SUPPLY_STATUS" == "Full" ]
        then return
        fi
        if [ "$POWER_SUPPLY_CAPACITY" -gt 10 ]
        then return
        fi
        content="$content
$bat $POWER_SUPPLY_STATUS $POWER_SUPPLY_CAPACITY%"
    done
    return 1
}

while true
do
    content=""
    check || notify-send "Battery Low:$content"
    sleep 60
done
