#!/bin/bash

cd /sys/class/power_supply

while true
do
    content="Battery Low:"
    for bat in BAT*
    do
        source <(sed "s/=/='/;s/$/'/" "$bat/uevent")
        if [ "$POWER_SUPPLY_STATUS" != "Charging" -a \
             "$POWER_SUPPLY_STATUS" != "Full" ]
        then
            if [[ "$POWER_SUPPLY_CAPACITY" < 10 ]]
            then
                content="$content
$bat $POWER_SUPPLY_STATUS $POWER_SUPPLY_CAPACITY%"
            fi
        fi
    done
    if [ "$content" != "Battery Low:" ]
    then
        notify-send "$content"
    fi
    sleep 60
done
