#!/bin/bash

cd /sys/class/power_supply

if [ ! -d AC ]
then exit
fi

check () {
    if [ "$(cat AC/online)" == "1" ]
    then return
    fi
    for bat in BAT*
    do
        source <(sed "s/=/='/;s/$/'/" "$bat/uevent")
        if [ "$POWER_SUPPLY_STATUS" == "Discharging" ]
        then break  # if any battery is discharging, report its percentage
        fi
    done
    if [ "$POWER_SUPPLY_STATUS" == "Charging" ]
    then return
    fi
    if [ "$POWER_SUPPLY_STATUS" == "Full" ]
    then return
    fi
    if [ "$POWER_SUPPLY_CAPACITY" -gt 10 ]
    then return
    fi
    content="$content
$bat $POWER_SUPPLY_STATUS $POWER_SUPPLY_CAPACITY%"
    return 1
}

if [ -n "$1" ]  # pass an argument to see output in terminal
then
    check
    echo $content
    exit
fi

while true
do
    content=""
    check || notify-send "Battery Low:$content"
    sleep 60
done
