#!/bin/bash
#
# When I hit the Win+Space keyboard shortcut in FVWM, a simple terminal
# window comes up whose content is printed by this script.

# Clear screen.
clear

while true
do
    # Jump back to upper left corner.
    printf "\033[1;1H"
    echo
    echo "         AUS            UTC          Eastern        Pacific"
    echo "     $(TZ=Australia/Sydney date +'%Y %b %d')    $(TZ=UTC date +'%Y %b %d')    $(TZ=US/Eastern date +'%Y %b %d')    $(TZ=US/Pacific date +'%Y %b %d')"
    echo "        $(TZ=Australia/Sydney date +'%H:%M')          $(TZ=UTC date +'%H:%M')          $(TZ=US/Eastern date +'%H:%M')          $(TZ=US/Pacific date +'%H:%M')"
    echo
    script --quiet --command 'cal -3' ~/.fvwm/.calendar >/dev/null
    sed '1d;/Script done/d;/^$/d;s/^/  /' ~/.fvwm/.calendar
    shopt -s nullglob
    for bat in /sys/class/power_supply/BAT*
    do
        source <(sed "s/=/='/;s/$/'/" "$bat/uevent")
        echo -n "                      "
        echo -n $POWER_SUPPLY_NAME ${POWER_SUPPLY_CAPACITY}% $POWER_SUPPLY_STATUS
        if [ "$POWER_SUPPLY_STATUS" == "Discharging" ]
        then
            m=$(($POWER_SUPPLY_ENERGY_NOW * 60 / $POWER_SUPPLY_POWER_NOW + 1))
            echo -n " $m minutes"
        fi
        echo
    done
    sleep $(( 60 - $(date +%S | sed s/^0//) ))
done
