#!/usr/bin/bash

# Clear screen.
clear

while true
do
    # Jump back to upper left corner.
    printf "\033[1;1H"
    echo
    echo "         AUS            UTC          Eastern        Pacific"
    echo "     $(TZ=Australia/Sydney date +'%Y %b %d')    $(TZ=UTC date +'%Y %b %d')    $(TZ=US/Eastern date +'%Y %b %d')    $(TZ=US/Pacific date +'%Y %b %d')"
    echo "        $(TZ=Australia/Sydney date +'%H:%M')          $(TZ=UTC date +'%H:%M')          $(TZ=US/Eastern date +'%H:%M')          $(TZ=US/Pacific date +'%H:%M')"
    echo
    script --quiet --command 'cal -3' ~/.fvwm/.calendar >/dev/null
    sed '1d;/Script done/d;/^$/d;s/^/  /' ~/.fvwm/.calendar
    for bat in /sys/class/power_supply/BAT*
    do
        source <(sed "s/=/='/;s/$/'/" "$bat/uevent")
        echo -n "                      "
        echo $POWER_SUPPLY_NAME ${POWER_SUPPLY_CAPACITY}% $POWER_SUPPLY_STATUS
    done
    sleep $(( 60 - $(date +%S | sed s/^0//) ))
done
